/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial1;

import org.junit.Test;
import static org.junit.Assert.*;

public class HanoiTest {
    @Test
    public void testHowMany() {
        assertEquals(new Hanoi(1).howMany(), 1);
        assertEquals(new Hanoi(2).howMany(), 3);
        assertEquals(new Hanoi(3).howMany(), 7);
        assertEquals(new Hanoi(5).howMany(), 31);
        assertEquals(new Hanoi(6).howMany(), 63);
        assertEquals(new Hanoi(7).howMany(), 127);
        assertEquals(new Hanoi(8).howMany(), 255);
        assertEquals(new Hanoi(9).howMany(), 511);
        assertEquals(new Hanoi(10).howMany(), 1023);
    }
}
