/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class EsreverTest {
    @Test
    public void testSomeLibraryMethod() {
        assertEquals(Esrever.reverse("gear"), "raeg");
        assertEquals(Esrever.reverse("abc"), "cba");
        assertEquals(Esrever.reverse("12312"), "21321");
    }
}
