/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class ScrableWinnerTest {
    @Test
    public void testSomeLibraryMethod() {
        assertEquals(ScrableWinner.evaluate("gear"), 5);
        assertEquals(ScrableWinner.evaluate("apple"), 9);
        assertEquals(ScrableWinner.evaluate("queen"), 14);
        assertEquals(ScrableWinner.evaluate("koala"), 9);
        assertEquals(ScrableWinner.evaluate("object"), 17);
    }
}
